### ISSUE TITLE
"Umbraco" is a reserved prefix on Nuget

### ISSUE THREAD

**Issue by ahwm** [LottePitcher/opinionated-package-starter#11]
### Bug description

Consider using something more like "Our.Umbraco.PackageName" since the "Umbraco" prefix is reserved and the default configuration of the package starter will error out when publishing. I ran into that myself on my first package.

**Comment by LottePitcher** [comment]
Hullo @ahwm,

Thanks for your feedback. And until a couple of months ago you would have been completely right. However Umbraco have now told nuget to allow anyone to release packages with the 'Umbraco.Community' prefix.

Anything else starting 'Umbraco' is still reserved.

So perhaps you can drop the 'Our' from your next package!

**Comment by ahwm** [comment]
Ah. Hadn't heard that. Good to know!
